### ISSUE TITLE
正文字体大小调整

### ISSUE THREAD

**Issue by msailim** [lineshjose/WordStar#1]
您好，我个人觉得该主题正文字体太小了，像调整以下，您知道该编辑那块文件吗？

**Comment by lineshjose** [comment]
Hi, I'm not sure what you looking for, the translation is not good. Please explain your issues in English. 

Thanks :)

**Comment by msailim** [comment]
> 嗨，我不确定你在找什么，翻译不好。请用英语解释您的问题。
> 
> 谢谢 ：）

sorry,I forgot that,my issues is that The  text size of the theme is too small，I want change that, but I don't know which file to edit.so  I am looking for your help.thank you.

**Comment by lineshjose** [comment]
Hi,

"**style.css**" is the main CSS file. There you can edit font sizes. Also please check "**/assets/css/**" files for additional edit.

I'm not suggesting to edit theme files because if you update to new version the changes will be replaced. Please use plugins like "**Advanced CSS Editor**" to edit style.

Best,

**Comment by msailim** [comment]
> 嗨，
> 
> “ **style.css** ”是主要的CSS文件。在那里你可以编辑字体大小。另请检查“ **/ assets / css /** ”文件以进行其他编辑。
> 
> 我不建议编辑主题文件，因为如果您更新到新版本，更改将被替换。请使用“ **高级CSS编辑器** ” 等插件来编辑样式。
> 
> 最好，

thank you for your help.you are right,last time the changes was replacde when I update. i will ues Advanced CSS Editor to edit style, but,this is my little suggestion：The text size of the theme is bit small,Large fonts look better. finally,thanks for your simple and beautiful theme.

**Comment by lineshjose** [comment]
Hi,
Suggestion noted. Thanks for using WordStar :)
